INSERT INTO ZAHTEV(ime, prezime, adresa, grad, drzava, telefon, email, password, jbzo, verified) VALUES
    ('dsads', 'dssadsa', 'dsadsa', 'dsadffds', 'fsdgdf', 'fdssd', 'fdsfds@gmail.com', 'fdsfsd', '2132131', False);
INSERT INTO AUTHORITY VALUES ('1', 'ROLE_PACIJENT');
INSERT INTO AUTHORITY VALUES ('2', 'ROLE_LEKAR');
INSERT INTO AUTHORITY VALUES ('3', 'ROLE_AK');
INSERT INTO AUTHORITY VALUES ('4', 'ROLE_AKC');
INSERT INTO AUTHORITY VALUES ('5', 'ROLE_MED_SESTRA');
INSERT INTO KORISNIK VALUES ('1', 'adresa admina KC', 'Srbija', 'adminKC@gmail.com', 'Novi Sad', 'Admin', '$2a$10$feiotRqclqYZ7aJnytCDSedhWmzztzhuwyujbVfVucV4nbmMRNnwa', 'Centric', '123456');
INSERT INTO USER_AUTHORITY VALUES ('1', '4');
INSERT INTO KORISNIK VALUES ('2', 'adresa admina', 'Srbija', 'adminKlinike@gmail.com', 'Novi Sad', 'Admin', '$2a$10$feiotRqclqYZ7aJnytCDSedhWmzztzhuwyujbVfVucV4nbmMRNnwa', 'Adminic', '123456');
INSERT INTO ADMIN_KLIN_CENTRA VALUES ('1', '1');
INSERT INTO USER_AUTHORITY VALUES ('2', '3');
INSERT INTO KLINIKA VALUES ('1', 'adresa klinike', 'Naziv klinike', 'opis klinike', '1');
INSERT INTO ADMIN_KLINIKE VALUES ('1', '1', '1', '2');
INSERT INTO KORISNIK VALUES ('3', 'adresa lekara', 'Srbija', 'lekar@gmail.com', 'Novi Sad', 'Lekar', '$2a$10$feiotRqclqYZ7aJnytCDSedhWmzztzhuwyujbVfVucV4nbmMRNnwa', 'Lekaric', '123456' );
INSERT INTO USER_AUTHORITY VALUES ('3', '2');
INSERT INTO LEKAR VALUES ('1', '1', '3');
INSERT INTO KORISNIK VALUES ('4', 'adresa pacijenta', 'Srbija', 'pacijent@gmail.com', 'Novi Sad', 'Pacijent', '$2a$10$feiotRqclqYZ7aJnytCDSedhWmzztzhuwyujbVfVucV4nbmMRNnwa', 'Pacijentic', '123456');
INSERT INTO USER_AUTHORITY VALUES ('4', '1');
INSERT INTO PACIJENT VALUES ('1', '2019-11-20', '1234', '1', '4');
INSERT INTO KORISNIK VALUES ('5', 'adresa med sestre', 'Srbija', 'medsestra@gmail.com', 'Novi Sad', 'Sestra', '$2a$10$feiotRqclqYZ7aJnytCDSedhWmzztzhuwyujbVfVucV4nbmMRNnwa', 'Sestric', '123456');
INSERT INTO USER_AUTHORITY VALUES ('5', '5');
INSERT INTO MEDICINSKA_SESTRA VALUES ('1','1', '5');