export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const SET_ERROR = "SET_ERROR";
export const SET_REAL_KORISNIK = "SET_REAL_KORISNIK";

export const SET_ZAHTEV_LOADING = "SET_ZAHTEV_LOADING";
export const SET_ALL_ZAHTEV = "GET_ALL_ZAHTEV";

export const DELETE_ZAHTEV = "DELETE_ZAHTEV";

export const SET_PACIJENT_PROFILE = "SET_PACIJENT_PROFILE";

export const SET_EDIT_PACIJENT = "SET_EDIT_PACIJENT";
