export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const SET_ERROR = "SET_ERROR";
export const SET_REAL_KORISNIK = "SET_REAL_KORISNIK";

export const SET_ZAHTEV_LOADING = "SET_ZAHTEV_LOADING";
export const SET_ALL_ZAHTEV = "GET_ALL_ZAHTEV";

export const DELETE_ZAHTEV = "DELETE_ZAHTEV";

export const SET_PACIJENT_PROFILE = "SET_PACIJENT_PROFILE";
export const SET_EDIT_PACIJENT = "SET_EDIT_PACIJENT";
export const SET_PACIJENT_ZDR = "SET_PACIJENT_ZDR";

export const SET_LEKAR_PROFILE = "SET_LEKAR_PROFILE";
export const SET_EDIT_LEKAR = "SET_EDIT_LEKAR";
export const SET_LEKAR_LIST = "SET_LEKAR_LIST";
export const SET_LEKARI_ZA_OPERACIJU = "SET_LEKARI_ZA_OPERACIJU";

export const SET_MEDSESTRA_PROFILE = "SET_MEDSESTRA_PROFILE";
export const SET_EDIT_MEDSESTRA = "SET_EDIT_MEDSESTRA";

export const SET_ALL_KLINIKE = "SET_ALL_KLINIKE";
export const SET_ADDED_KLINIKA = "SET_ADDED_KLINIKA";

export const SET_ALL_ADMINK = "SET_ALL_ADMINK";
export const SET_ADDED_ADMINK = "SET_ADDED_ADMINK";

export const SET_ALL_ADMINKC = "SET_ALL_ADMINKC";
export const SET_ADDED_ADMINKC = "SET_ADDED_ADMINKC";

export const SET_ZDRKARTON = "SET_ZDRKARTON";

export const SET_ADMINOVA_KLINIKA = "SET_ADMINOVA_KLINIKA";
export const SET_EDIT_KLINIKA = "SET_EDIT_KLINIKA";

export const USER_LOGOUT = "USER_LOGOUT";

export const SET_ALL_TIPOVI_PREGLEDA = "SET_ALL_TIPOVI_PREGLEDA";
export const SET_ADDED_LEKAR = "SET_ADDES_LEKAR";

export const SET_ADDED_SALA = "SET_ADDED_SALA";
export const SET_KLINIKA = "SET_KLINIKA";

export const SET_PREGLED = "SET_PREGLED";
export const SET_OPERACIJA = "SET_OPERACIJA";

export const SET_PREGLEDI = "SET_PREGLEDI";
export const SET_OPERACIJE = "SET_OPERACIJE";

export const SET_ALL_TIPOVI = "SET_ALL_TIPOVI";
export const SET_ADDED_TIP_PREGLEDA = "SET_ADDED_TIP_PREGLEDA";
export const SET_FILTERED_PREGLEDI = "SET_FILTERED_PREGLEDI";
export const SET_FILTERED_PREDEFINISANI = "SET_FILTERED_PREDEFINISANI";

export const SET_LEKARI_NA_KLINICI = "SET_LEKARI_NA_KLINICI";
export const SET_EDITED_LEKAR = "SET_EDITED_LEKAR";

export const SET_LISTA_SALA = "SET_LISTA_SALA";

export const SET_LEKAR_ZA_PREGLED = "SET_LEKAR_ZA_PREGLED";

export const SET_PREGLEDI_ZA_SALU = "SET_PREGLEDI_ZA_SALU";
export const SET_OPERACIJE_ZA_SALU = "SET_OPERACIJE_ZA_SALU";

export const SET_TERMIN_ZA_PREGLED = "SET_TERMIN_ZA_PREGLED";
export const SET_LISTA_DOSTUPNIH_SALA = "SET_LISTA_DOSTUPNIH_SALA";

export const SET_SALA_ZA_PREGLED = "SET_SALA_ZA_PREGLED";

export const SET_LISTA_DOSTUPNIH_SESTARA = "SET_LISTA_DOSTUPNIH_SESTARA";
export const SET_SESTRA_ZA_PREGLED = "SET_SESTRA_ZA_PREGLED";

export const SET_LISTA_LEKOVA = "SET_LISTA_LEKOVA";
export const SET_LEK = "SET_LEK";

export const SET_DIJAGNOZA = "SET_DIJAGNOZA";
export const SET_ALL_DIJAGNOZE = "SET_ALL_DIJAGNOZE";

export const SET_LISTA_PREDEFINISANIH_PREGLEDA =
  "SET_LISTA_PREDEFINISANIH_PREGLEDA";

export const SET_LEKARI_KOJI_SE_MOGU_OBRISATI =
  "SET_LEKARI_KOJI_SE_MOGU_OBRISATI";

export const SET_OBRISAN_LEKAR = "SET_OBRISAN_LEKAR";

export const SET_SALE_KOJE_SE_MOGU_OBRISATI = "SET_SALE_KOJE_SE_MOGU_OBRISATI";
export const SET_OBRISANA_SALA = "SET_OBRISANA_SALA";

export const SET_EDITED_SALA = "SET_EDITED_SALA";
export const SET_TIPOVI_KOJI_SE_MOGU_IZMENITI =
  "SET_TIPOVI_KOJI_SE_MOGU_IZMENITI";
export const SET_EDITED_TIP = "SET_EDITED_TIP";

export const SET_ODMOR = "SET_ODMOR";
export const SET_ODSUSTVO = "SET_ODSUSTVO";

export const SET_ZAHTEVI_ADMIN_ODMOR = "SET_ZAHTEVI_ADMIN_ODMOR";
export const SET_ZAHTEVI_ADMIN_ODSUSTVO = "SET_ZAHTEVI_ADMIN_ODSUSTVO";

export const SET_ZAHTEV_ODMOR = "SET_ZAHTEV_ODMOR";
export const SET_ZAHTEV_ODSUSTVO = "SET_ZAHTEV_ODSUSTVO";

export const SET_PREGLEDI_LEKAR = "SET_PREGLEDI_LEKAR";
export const SET_PREGLEDI_SESTRA = "SET_PREGLEDI_SESTRA";

export const SET_OPERACIJE_LEKAR = "SET_OPERACIJE_LEKAR";
export const SET_OPERACIJE_SESTRA = "SET_OPERACIJE_SESTRA";

export const SET_ODBIJEN_ZAHTEV_ODSUSTVO = "SET_ODBIJEN_ZAHTEV_ODSUSTVO";
export const SET_PRIHVACEN_ZAHTEV_ODSUSTVO = "SET_PRIHVACEN_ZAHTEV_ODSUSTVO";

export const SET_PREGLEDI_LEKAR_ODMOR = "SET_PREGLEDI_LEKAR_ODMOR";
export const SET_PREGLEDI_SESTRA_ODMOR = "SET_PREGLEDI_SESTRA_ODMOR";

export const SET_OPERACIJE_LEKAR_ODMOR = "SET_OPERACIJE_LEKAR_ODMOR";
export const SET_OPERACIJE_SESTRA_ODMOR = "SET_OPERACIJE_SESTRA_ODMOR";

export const SET_ODBIJEN_ZAHTEV_ODMOR = "SET_ODBIJEN_ZAHTEV_ODMOR";
export const SET_PRIHVACEN_ZAHTEV_ODMOR = "SET_PRIHVACEN_ZAHTEV_ODMOR";

export const SET_ZAVRSEN_PREGLED_OPERACIJA = "SET_ZAVRSEN_PREGLED_OPERACIJA";
export const SET_ZAPOCET_PREGLED_OPERACIJA = "SET_ZAPOCET_PREGLED_OPERACIJA";
export const SET_ZAVRSENI_PREGLEDI = "SET_ZAVRSENI_PREGLEDI";
export const SET_ZAVRSENE_OPERACIJE = "SET_ZAVRSENE_OPERACIJE";

export const SET_OBRISAN_TIP = "SET_OBRISAN_TIP";

export const SET_RECEPTI = "SET_RECEPTI";
export const SET_OVEREN_RECEPT = "SET_OVEREN_RECEPT";

export const SET_PREGLEDAO_PACIJENTA = "SET_PREGLEDAO_PACIJENTA";
export const SET_ISPRAVI_ZAPOCET_PREGLED = "SET_ISPRAVI_ZAPOCET_PREGLED";
export const SET_ISPRAVI_ZAPOCETA_OPERACIJA = "SET_ISPRAVI_ZAPOCETA_OPERACIJA";

export const SET_TERMIN_ZA_OPERACIJU = "SET_TERMIN_ZA_OPERACIJU";
export const SET_PREGLEDI_PRONALAZENJE_SALE = "SET_PREGLEDI_PRONALAZENJE_SALE";
export const SET_OPERACIJE_PRONALAZENJE_SALE =
  "SET_OPERACIJE_PRONALAZENJE_SALE";

export const SET_GRAFIK = "SET_GRAFIK";
export const SET_ADMIN_KLINIKE = "SET_ADMIN_KLINIKE";
export const SET_EDIT_ADMIN_KLINIKE = "SET_EDIT_ADMIN_KLINIKE";

export const SET_ADMIN_KC = "SET_ADMIN_KC";
export const SET_EDITED_ADMIN_KC = "SET_EDITED_ADMIN_KC";
