export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const SET_ERROR = "SET_ERROR";
export const SET_REAL_KORISNIK = "SET_REAL_KORISNIK";

export const SET_ZAHTEV_LOADING = "SET_ZAHTEV_LOADING";
export const SET_ALL_ZAHTEV = "GET_ALL_ZAHTEV";

export const DELETE_ZAHTEV = "DELETE_ZAHTEV";

export const SET_PACIJENT_PROFILE = "SET_PACIJENT_PROFILE";
export const SET_EDIT_PACIJENT = "SET_EDIT_PACIJENT";

export const SET_LEKAR_PROFILE = "SET_LEKAR_PROFILE";
export const SET_EDIT_LEKAR = "SET_EDIT_LEKAR";

export const SET_MEDSESTRA_PROFILE = "SET_MEDSESTRA_PROFILE";
export const SET_EDIT_MEDSESTRA = "SET_EDIT_MEDSESTRA";

export const SET_ALL_KLINIKE = "SET_ALL_KLINIKE";
export const SET_ADDED_KLINIKA = "SET_ADDED_KLINIKA";

export const SET_ALL_ADMINK = "SET_ALL_ADMINK";
export const SET_ADDED_ADMINK = "SET_ADDED_ADMINK";

export const SET_ZDRKARTON = "SET_ZDRKARTON";

export const SET_ADMINOVA_KLINIKA = "SET_ADMINOVA_KLINIKA";
export const SET_EDIT_KLINIKA = "SET_EDIT_KLINIKA";
